# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('test_date', models.DateField()),
                ('laboratory_name', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lab_results',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('file_name', models.CharField(max_length=250)),
                ('file_type', models.CharField(help_text='e.g. application/pdf, image/jpeg', max_length=100)),
                ('document_type', models.CharField(choices=[('LAB_RESULT', 'Kết quả xét nghiệm'), ('PRESCRIPTION', 'Đơn thuốc'), ('DISCHARGE', 'Giấy xuất viện'), ('IMAGING', 'Chẩn đoán hình ảnh'), ('OTHER', 'Khác')], default='LAB_RESULT', max_length=50)),
                ('storage_url', models.CharField(max_length=500)),
                ('is_parsed', models.BooleanField(default=False)),
                ('uploaded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('record_type', models.CharField(choices=[('CONSULTATION_NOTE', 'Ghi chú khám'), ('EXTERNAL_DOC', 'Tài liệu bên ngoài'), ('DISCHARGE_SUMMARY', 'Tóm tắt xuất viện'), ('SURGERY_REPORT', 'Báo cáo phẫu thuật')], default='CONSULTATION_NOTE', max_length=50)),
                ('created_by', models.UUIDField(help_text='User ID of doctor/creator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='bpm', null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, help_text='Celsius', max_digits=4, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='breaths/min', null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='SpO2 %', null=True)),
                ('recorded_by', models.UUIDField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vitals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text='e.g. glucose, HbA1c, RBC', max_length=200)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_range', models.CharField(blank=True, help_text='e.g. 70-100 mg/dL', max_length=100)),
                ('status', models.CharField(choices=[('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('LOW', 'Thấp'), ('CRITICAL', 'Nguy kịch')], default='NORMAL', max_length=20)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.labresult')),
            ],
            options={
                'db_table': 'lab_result_items',
            },
        ),
    ]
