# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. APPOINTMENT_CONFIRMED', max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'Tin nhắn SMS'), ('EMAIL', 'Thư điện tử'), ('PUSH', 'Thông báo ứng dụng')], max_length=20)),
                ('subject_template', models.CharField(blank=True, help_text='Subject template (mainly for email)', max_length=250)),
                ('body_template', models.TextField(help_text='Body content with variables like {{patient_name}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.UUIDField()),
                ('channel', models.CharField(choices=[('SMS', 'Tin nhắn SMS'), ('EMAIL', 'Thư điện tử'), ('PUSH', 'Thông báo ứng dụng')], max_length=20)),
                ('recipient_address', models.CharField(help_text='Email address or phone number', max_length=250)),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Key-value variables to render template')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ gửi'), ('SENT', 'Đã gửi'), ('FAILED', 'Thất bại'), ('RETRYING', 'Đang thử lại')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('response_payload', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notificationjob')),
            ],
            options={
                'db_table': 'delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
