# Generated by Django 4.2 on 2026-07-29 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDSConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_id', models.UUIDField(help_text='ID phiên khám từ consultation-service')),
                ('provider_id', models.UUIDField(help_text='ID bác sĩ')),
                ('patient_id', models.UUIDField(help_text='ID bệnh nhân')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('COMPLETED', 'Đã đóng'), ('ARCHIVED', 'Đã lưu trữ')], default='ACTIVE', max_length=20)),
                ('patient_context_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot dị ứng, bệnh nền, thuốc của BN khi mở chat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cds_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CDSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'Hệ thống'), ('doctor', 'Bác sĩ'), ('assistant', 'Trợ lý AI')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Thông tin bổ sung (tokens, confidence...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cds.cdsconversation')),
            ],
            options={
                'db_table': 'cds_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('icd_code', models.CharField(blank=True, help_text='Mã ICD-10', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('severity_level', models.CharField(choices=[('MILD', 'Nhẹ'), ('MODERATE', 'Trung bình'), ('SEVERE', 'Nặng'), ('CRITICAL', 'Nguy kịch')], default='MODERATE', max_length=20)),
                ('is_chronic', models.BooleanField(default=False, help_text='Bệnh mãn tính')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên hoạt chất / biệt dược', max_length=250, unique=True)),
                ('atc_code', models.CharField(blank=True, help_text='Mã ATC', max_length=20)),
                ('drug_class', models.CharField(blank=True, help_text='Nhóm thuốc (Kháng sinh, Hạ áp...)', max_length=150)),
                ('dosage_forms', models.CharField(blank=True, help_text='Dạng bào chế (Viên nén, Si-rô...)', max_length=200)),
                ('common_dosage', models.CharField(blank=True, help_text='Liều dùng tham khảo', max_length=200)),
                ('contraindications_text', models.TextField(blank=True, help_text='Chống chỉ định chung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drugs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('body_system', models.CharField(blank=True, help_text='Hệ cơ quan (Hô hấp, Tim mạch...)', max_length=100)),
                ('is_red_flag', models.BooleanField(default=False, help_text='Triệu chứng cờ đỏ / nguy hiểm')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'symptoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugAllergenCrossRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(help_text='Tên nhóm dị ứng (Penicillin, Sulfa...)', max_length=200)),
                ('cross_reactivity_probability', models.DecimalField(decimal_places=2, default=0.1, help_text='Tỷ lệ phản ứng chéo (0.0-1.0)', max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_cross_refs', to='cds.drug')),
            ],
            options={
                'db_table': 'drug_allergen_cross_refs',
            },
        ),
        migrations.CreateModel(
            name='CDSRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('DRUG_INTERACTION', 'Tương tác thuốc'), ('ALLERGY_ALERT', 'Cảnh báo dị ứng'), ('DIFFERENTIAL_DIAGNOSIS', 'Gợi ý chẩn đoán phân biệt'), ('LAB_INTERPRETATION', 'Diễn giải xét nghiệm'), ('TREATMENT_SUGGESTION', 'Gợi ý điều trị'), ('DOSAGE_WARNING', 'Cảnh báo liều dùng'), ('GENERAL_ADVICE', 'Tư vấn chung')], default='GENERAL_ADVICE', max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Thông tin'), ('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Nguy kịch')], default='MEDIUM', max_length=20)),
                ('summary', models.CharField(help_text='Tóm tắt ngắn gọn khuyến nghị', max_length=300)),
                ('explanation', models.TextField(blank=True, help_text='Giải thích chi tiết')),
                ('confidence', models.DecimalField(decimal_places=2, default=0.85, help_text='Độ tin cậy của AI (0.0-1.0)', max_digits=3)),
                ('doctor_action', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('ACCEPTED', 'Đã chấp nhận'), ('IGNORED', 'Đã bỏ qua'), ('EDITED', 'Đã chỉnh sửa')], default='PENDING', max_length=20)),
                ('doctor_note', models.TextField(blank=True, help_text='Ghi chú của bác sĩ khi phản hồi')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cds.cdsconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cds.cdsmessage')),
            ],
            options={
                'db_table': 'cds_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('MINOR', 'Nhẹ — Theo dõi'), ('MODERATE', 'Trung bình — Thận trọng'), ('MAJOR', 'Nặng — Tránh dùng cùng'), ('CRITICAL', 'Chống chỉ định tuyệt đối')], default='MODERATE', max_length=20)),
                ('mechanism', models.TextField(blank=True, help_text='Cơ chế tương tác')),
                ('clinical_effect', models.TextField(blank=True, help_text='Hậu quả lâm sàng (ví dụ: Tăng nguy cơ chảy máu)')),
                ('recommendation', models.TextField(blank=True, help_text='Khuyên dùng / Giải pháp thay thế')),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='cds.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='cds.drug')),
            ],
            options={
                'db_table': 'drug_interactions',
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_of_treatment', models.CharField(choices=[('1ST_LINE', 'Lựa chọn đầu tay'), ('2ND_LINE', 'Lựa chọn hàng 2'), ('ALTERNATIVE', 'Thay thế')], default='1ST_LINE', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_mappings', to='cds.disease')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_treatments', to='cds.drug')),
            ],
            options={
                'db_table': 'disease_treatments',
                'unique_together': {('disease', 'drug')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('ALWAYS', 'Luôn có (100%)'), ('OFTEN', 'Thường gặp (>70%)'), ('SOMETIMES', 'Đôi khi (30-70%)'), ('RARE', 'Hiếm gặp (<30%)')], default='OFTEN', max_length=20)),
                ('specificity', models.DecimalField(decimal_places=2, default=0.5, help_text='Độ đặc hiệu (0.00-1.00)', max_digits=3)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_mappings', to='cds.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_mappings', to='cds.symptom')),
            ],
            options={
                'db_table': 'disease_symptoms',
                'unique_together': {('disease', 'symptom')},
            },
        ),
    ]
