# Generated by Django 4.2 on 2026-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdsconversation',
            name='consultation_id',
            field=models.UUIDField(blank=True, help_text='ID phiên khám từ consultation-service', null=True),
        ),
        migrations.AlterField(
            model_name='cdsconversation',
            name='patient_id',
            field=models.UUIDField(blank=True, help_text='ID bệnh nhân', null=True),
        ),
        migrations.AlterField(
            model_name='cdsconversation',
            name='provider_id',
            field=models.UUIDField(blank=True, help_text='ID bác sĩ', null=True),
        ),
    ]
