# Generated by Django 5.2.16 on 2026-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlicense',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
