# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='e.g. BASIC_MONTHLY, PRO_ANNUAL', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in VND', max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Hàng tháng'), ('ANNUALLY', 'Hàng năm')], default='MONTHLY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(help_text='e.g. VISITS_LIMIT, AI_CDS_ACCESS', max_length=100)),
                ('value', models.CharField(help_text='Limit value or Boolean status', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'plan_entitlements',
                'unique_together': {('plan', 'feature_code')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('TRIAL', 'Dùng thử'), ('EXPIRED', 'Hết hạn'), ('CANCELLED', 'Đã hủy')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_limit', models.IntegerField(default=0, help_text='0 means unlimited or boolean')),
                ('current_usage', models.IntegerField(default=0)),
                ('reset_at', models.DateTimeField()),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.planentitlement')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_usages',
                'unique_together': {('subscription', 'entitlement')},
            },
        ),
    ]
