# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(unique=True)),
                ('patient_id', models.UUIDField()),
                ('provider_id', models.UUIDField()),
                ('status', models.CharField(choices=[('DRAFT', 'Lịch nháp'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn tất')], default='DRAFT', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. 2 times a day', max_length=100)),
                ('duration_days', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('instructions', models.TextField(blank=True, help_text='Usage instructions')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_text', models.CharField(max_length=300)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 code', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='consultations.consultation')),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True, help_text='Symptom descriptions, patient history')),
                ('objective', models.TextField(blank=True, help_text='Vitals, physical exams, lab reviews')),
                ('assessment', models.TextField(blank=True, help_text='Differential diagnoses, progression analysis')),
                ('plan', models.TextField(blank=True, help_text='Therapy, follow-ups, diagnostic orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='consultations.consultation')),
            ],
            options={
                'db_table': 'clinical_notes',
            },
        ),
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('IGNORED', 'Ignored'), ('EDITED', 'Edited')], max_length=20)),
                ('doctor_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='consultations.consultation')),
            ],
            options={
                'db_table': 'ai_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
