# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(help_text='Patient ID from patient-service')),
                ('provider_id', models.UUIDField(help_text='Doctor/Provider ID from provider-service')),
                ('service_id', models.UUIDField(help_text='Service ID from provider-service')),
                ('status', models.CharField(choices=[('DRAFT', 'Lịch nháp'), ('HELD', 'Slot đang được giữ tạm'), ('PAYMENT_PENDING', 'Chờ thanh toán'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy'), ('COMPLETED', 'Đã hoàn tất khám'), ('NO_SHOW', 'Không tham gia'), ('REFUND_PENDING', 'Đang xử lý hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền')], default='HELD', max_length=30)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('FREE', 'Trống'), ('HELD', 'Đang giữ tạm'), ('BOOKED', 'Đã đặt')], default='FREE', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('provider_id', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField(help_text='Doctor/Provider ID from provider-service')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_schedules',
                'unique_together': {('provider_id', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Lịch nháp'), ('HELD', 'Slot đang được giữ tạm'), ('PAYMENT_PENDING', 'Chờ thanh toán'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy'), ('COMPLETED', 'Đã hoàn tất khám'), ('NO_SHOW', 'Không tham gia'), ('REFUND_PENDING', 'Đang xử lý hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.UUIDField(blank=True, help_text='User ID who made change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.timeslot'),
        ),
    ]
