# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('accessed_by_user_id', models.UUIDField()),
                ('accessed_by_role', models.CharField(max_length=30)),
                ('action', models.CharField(default='VIEW_MEDICAL_RECORD', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField()),
                ('actor_role', models.CharField(choices=[('PATIENT', 'Bệnh nhân'), ('DOCTOR', 'Bác sĩ'), ('ADMIN', 'Admin Marketplace'), ('PROVIDER_ADMIN', 'Provider Admin'), ('SYSTEM', 'Hệ thống')], max_length=30)),
                ('action', models.CharField(help_text='e.g. VIEW_MEDICAL_RECORD, UPDATE_PASSWORD', max_length=150)),
                ('resource_type', models.CharField(help_text='e.g. PATIENT_RECORD, APPOINTMENT', max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='SUCCESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='e.g. MFA_FAILED, BRUTE_FORCE', max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Nguy hiểm')], default='MEDIUM', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
