# Generated by Django 4.2 on 2026-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('appointment_id', models.UUIDField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Đã nộp'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Bị từ chối'), ('PAID', 'Đã chi trả')], default='SUBMITTED', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('provider_name', models.CharField(help_text='e.g. Bảo Việt, Prudential', max_length=200)),
                ('policy_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Còn hiệu lực'), ('EXPIRED', 'Hết hiệu lực'), ('PENDING', 'Chờ xử lý')], default='ACTIVE', max_length=20)),
                ('co_pay_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 20.00 for 20% co-payment', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('provider_id', models.UUIDField(help_text='Doctor/Clinic provider checking eligibility')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Đủ điều kiện'), ('NOT_ELIGIBLE', 'Không đủ điều kiện')], default='ELIGIBLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='insurance.insurancepolicy')),
            ],
            options={
                'db_table': 'eligibility_checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance.claim')),
            ],
            options={
                'db_table': 'claim_items',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insurancepolicy'),
        ),
    ]
